pipeline:
  docker:
    image: plugins/docker
    force_tag: true

publish:
  docker:
    repo: registry.liskl.com/tstllc-base
    tag:
      - latest
#      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch: master

#    storage_driver: overlay
#  ecr:
#    image: plugins/ecr
#    access_key: ${AWS_ECR_ID}
#    secret_key: ${AWS_ECR_KEY}
#    region: us-east-1
#    repo: ${AWS_ECR_REPO}
