pipeline:
  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-base
#    tag:
#      - ${DRONE_BRANCH}-latest
#      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
#    force_tag: true

publish:
  docker:
    repo: registry.tstllc.net/llisk/alpine-base
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    tag:
      - latest
    when:
      branch:
        include: [ master, release/* ]

publish:
  docker:
    repo: registry.tstllc.net/llisk/alpine-base
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    tag:
      - ${DRONE_BRANCH}-latest
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master ]

#    storage_driver: overlay
#  ecr:
#    image: plugins/ecr
#    access_key: ${AWS_ECR_ID}
#    secret_key: ${AWS_ECR_KEY}
#    region: us-east-1
#    repo: ${AWS_ECR_REPO}
